apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      name: app-server
      labels:
        app: app-server
    spec:
      containers:
        - name: app-server
          image: cumuluscycles/k8s-app-server:1.0

---

apiVersion: v1
kind: Service
metadata:
  name: app-server-service
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
    - port: 3000        # port exposed on local machine
      targetPort: 3000  # port exposed in container
      nodePort: 30300 # 3000 - 32767
          
