apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: web-server
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: cumuluscycles/k8s-web-server:1.0

---

apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - port: 80        # port exposed on local machine
      targetPort: 80  # port exposed in container
      nodePort: 30080 # 3000 - 32767
          
