apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081        # port exposed on local machine
      targetPort: 8081  # port exposed in container
      nodePort: 30081