apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - port: 80        # port exposed on local machine
      targetPort: 80  # port exposed in container
      nodePort: 30080 # 3000 - 32767