apiVersion: v1
kind: Service
metadata:
  name: app-server-service
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
    - port: 3000        # port exposed on local machine
      targetPort: 3000  # port exposed in container
      nodePort: 30300 # 3000 - 32767